version: '3.8'

services:
  threat-intel-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: threat-intel-mcp-server
    ports:
      - "9090:9090"  # Metrics and health check port
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./intel_logs:/app/intel_logs
      - ./.env:/app/.env:ro
    environment:
      - PYTHONPATH=/app
      - INTEL_CONFIG_PATH=/app/config.yaml
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=50m
    networks:
      - threat-intel-network
    healthcheck:
      test: ["CMD", "python", "-c", "print('Health check OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   container_name: threat-intel-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - threat-intel-network
  #   command: redis-server --appendonly yes

  # Optional: Prometheus for metrics (uncomment if needed)
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: threat-intel-prometheus
  #   ports:
  #     - "9091:9090"
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #   networks:
  #     - threat-intel-network

volumes:
  redis_data:

networks:
  threat-intel-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16